services:
  - type: web
    name: mochan-labs-admin
    runtime: node
    plan: standard
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    region: oregon
    autoDeploy: true
